import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { isAuthenticated } from '@/app/utils/session';
import { redirect } from 'next/navigation';


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const isAuth = await isAuthenticated();
  
  if (isAuth) {
    redirect('/');
  }

  return (
    <html>
      <body>
        {children}
      </body>
    </html>
  );
}
