import type { Metadata } from "next";
import "../globals.css";
import { isAuthenticated } from "@/app/utils/session";
import { redirect } from "next/navigation";
import Sidebar from "./components/sidebar";
import Header from "./components/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const isAuth = await isAuthenticated();

  if (!isAuth) {
    redirect("/login");
  }

  return (
    <div className="flex flex-row ">
      <div className="w-1/4">
        <Sidebar />
      </div>
      <div className="w-full">
        <div className=" bg-gray-100">
          {/* Header component */}
          <Header />
        </div>
        <div>
          {/* Main content goes here */}
          {children}
        </div>
      </div>
    </div>
  );
}
